Repository neo4j/docs-bloom, pull requests merged in 2024-02, with the labels that each got.

#19 clarified browser URL
  modules/ROOT/pages/bloom-installation/bloom-deployment-modes.adoc
Labels: documentation

#20 Merge pull request #19 from AlexicaWright/docs-aura-typo
  modules/ROOT/pages/bloom-installation/bloom-deployment-modes.adoc
Labels: cherry-picked

#18 Fixing with new url in the operations manual
  modules/ROOT/pages/bloom-perspectives/perspective-storage.adoc
  package-lock.json
Labels: bug
